inherit_from: .rubocop_todo.yml

require:
  - 'rubocop-performance'

AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end

Lint/RescueException:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false # false positives

Style/SignalException:
  Exclude:
    - 'lib/redis/connection/synchrony.rb'

Style/StringLiterals:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ElseAlignment:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - lib/redis/connection/ruby.rb

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'test/**/*'

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Exclude:
    - cluster/redis-clustering.gemspec

Performance/AncestorsInclude: # new in 1.7
  Enabled: true
Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true
Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true
Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true
Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: true
Performance/ConstantRegexp: # new in 1.9
  Enabled: true
Performance/MapCompact: # new in 1.11
  Enabled: true
Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: true
Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true
Performance/RedundantSortBlock: # new in 1.7
  Enabled: true
Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true
Performance/RedundantStringChars: # new in 1.7
  Enabled: true
Performance/ReverseFirst: # new in 1.7
  Enabled: true
Performance/SortReverse: # new in 1.7
  Enabled: true
Performance/Squeeze: # new in 1.7
  Enabled: true
Performance/StringIdentifierArgument: # new in 1.13
  Enabled: true
Performance/StringInclude: # new in 1.7
  Enabled: true
Performance/Sum: # new in 1.8
  Enabled: true